# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShopifyiOSTemplate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShopifyiOSTemplate
  pod 'FSPagerView', '0.8.3'
  pod 'SideMenuSwift', '2.0.9'
  pod 'SVProgressHUD', '2.2.5'
  pod 'IQKeyboardManagerSwift', '6.5.7'
  pod 'Mobile-Buy-SDK', '11.0.0'
  pod 'Firebase/Firestore', '10.22.0'
  pod 'FirebaseMessaging', '10.22.0'
  pod 'Kingfisher'
  pod 'Cosmos', '~> 25.0'
  pod 'Alamofire', '~> 5.4'
end
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
    # From https://stackoverflow.com/a/73747611.
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
